
services:
  tag_game:
      image: tag_game
      container_name: tag_game
      build: ./tag-game
      ports:
        - 8007:8005
      volumes:
      - ./tag-game:/game
      command: python manage.py runserver 0.0.0.0:8005

volumes:
  tag_game:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./tag_game/project

networks:
  my_network:
    driver: bridge