
services:
  tag_game:
      image: tag_game
      container_name: tag_game
      build: ./tag-game
      ports:
        - 8007:8005
      volumes:
        - ./tag-game:/game

      command: python manage.py runserver 0.0.0.0:8005
      networks:
        - my_network

  tag_db:
      image: tag_db
      container_name: tagDb
      build: ./tag-db
      ports:
        - 8000:8000
      volumes:
        - ./tag-db:/db
      command: python manage.py runserver 0.0.0.0:8000
      networks:
        - my_network


volumes:
  tag_game:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./tag_game/project

networks:
  my_network:
    driver: bridge